[package]
name = "oc_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
druid = {version = "0.8.3", features = ["im", "svg", "image"]}
tokio = "1.40.0"
serde = "1.0.210"
once_cell = "1.19.0"
thiserror = "1.0.64"
whoami = "1.5.2"

winreg = "0.52.0"
directories = "5.0.1"
windows = { version = "0.58", features = [
    "Win32_Security",
    "Win32_System", 
    "Win32_System_GroupPolicy", 
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_Security_Authentication_Identity"
    ]}
anyhow = "1.0.89"


