[package]
name = "oc_tool"
version = "0.1.0"
edition = "2021"

[package.metadata.winres]
"manifest" = "app.manifest"

[dependencies]
druid = {version = "0.8.3", features = ["im", "svg", "image"]}
tokio = { version = "1.40", features = ["full"] }
serde = "1.0.210"
once_cell = "1.19.0"
thiserror = "1.0.64"
whoami = "1.5.2"

winreg = "0.52.0"
directories = "5.0.1"
windows = { version = "0.58", features = [
    "Win32_Security",
    "Win32_System", 
    "Win32_System_GroupPolicy", 
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_Security_Authentication_Identity",
    "Win32_Security_Authorization",
    "Win32_UI",
    "Win32_UI_Shell"
    ]}
anyhow = "1.0.89"
embed-resource = "2.4.3"
winapi = {version="0.3.9", features=["securitybaseapi"]}
tracing = "0.1.40"



