[package]
name = "oc_tool"
version = "0.1.0"
edition = "2021"

[package.metadata.winres]
"manifest" = "app.manifest"

[dependencies]
serde = "1.0.210"
once_cell = "1.19.0"
thiserror = "1.0.64"
whoami = "1.5.2"
winreg = "0.52.0"
directories = "5.0.1"
windows = { version = "0.58", features = [
    "Win32_Security",
    "Win32_System", 
    "Win32_System_GroupPolicy", 
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_Security_Authentication_Identity",
    "Win32_Security_Authorization",
    "Win32_UI",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging"
    ]}
anyhow = "1.0.89"
winapi = {version="0.3.9", features=[
    "securitybaseapi", 
    "winuser",
    "handleapi",
    "processthreadsapi",
    ]}
tracing = "0.1.40"
eframe = "0.28.1"
egui = "0.28.1"
crossbeam = "0.8.4"
fern = "0.6.2"
log = "0.4.22"
chrono = "0.4.38"

