name: Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release
        run: cargo build --profile release-lto

      - name: Ensure Additional Files Exist
        run: |
          if (!(Test-Path target\release-lto\WinRing0x64.sys)) {
            throw "WinRing0x64.sys not found!"
          }
          if (!(Test-Path target\release-lto\WinRing0x64.dll)) {
            throw "WinRing0x64.dll not found!"
          }

      - name: Create Release Zip
        shell: pwsh
        run: |
          $files = @(
            'target\release-lto\oc_tool.exe',
            'target\release-lto\WinRing0x64.sys',
            'target\release-lto\WinRing0x64.dll'
          )
          Compress-Archive -Path $files -DestinationPath oc_tool.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oc-tool
          path: oc_tool.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: oc-tool

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: oc_tool.zip
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_TOKEN }}
