name: Release

on:
  push:
    tags:
      - 'v*'   # This workflow triggers when you push a tag that starts with "v"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release
        run: cargo build --profile release-lto

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oc-tool
          path: target/release/oc_tool.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: oc-tool

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: oc_tool.exe
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_TOKEN }}
