name: Release

on:
  push:
    tags:
      - 'v*'   # This workflow triggers when you push a tag that starts with "v"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Build Release
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app
          path: target/release/oc-tool.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: my-app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
